# Generated by Django 4.2.7 on 2025-11-26 07:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('plan_type', models.CharField(choices=[('basic', 'Базовый'), ('business', 'Бизнес'), ('enterprise', 'Корпоративный')], max_length=20, unique=True)),
                ('max_employees', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимум сотрудников (null = безлимит)')),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена в месяц (тенге)')),
                ('features', models.JSONField(default=dict, verbose_name='Доступные функции')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'План подписки',
                'verbose_name_plural': 'Планы подписок',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('expired', 'Истекла'), ('cancelled', 'Отменена')], default='active', max_length=20, verbose_name='Статус')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='Автопродление')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.subscriptionplan', verbose_name='План')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'indexes': [models.Index(fields=['user', 'status'], name='subscriptio_user_id_2a19e8_idx'), models.Index(fields=['expires_at'], name='subscriptio_expires_53ce37_idx')],
            },
        ),
    ]
