# Generated by Django 4.2.7 on 2025-11-26 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_capacity_per_day_and_more'),
        ('subscriptions', '0002_remove_subscription_subscriptio_user_id_2a19e8_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='organizations.organization', verbose_name='Организация'),
        ),
    ]
