# Generated by Django 4.2.7 on 2025-11-26 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examination_type', models.CharField(choices=[('preliminary', 'Предварительный'), ('periodic', 'Периодический'), ('extraordinary', 'Внеочередной')], max_length=20, verbose_name='Тип осмотра')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирован'), ('in_progress', 'В процессе'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='scheduled', max_length=20, verbose_name='Статус')),
                ('scheduled_date', models.DateTimeField(verbose_name='Запланированная дата')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('result', models.CharField(blank=True, choices=[('fit', 'Годен'), ('unfit', 'Не годен'), ('limited', 'Годен с ограничениями')], max_length=20, null=True, verbose_name='Результат')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examinations', to='organizations.organization', verbose_name='Клиника')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Медицинский осмотр',
                'verbose_name_plural': 'Медицинские осмотры',
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
