# Generated by Django 4.2.7 on 2025-11-26 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_capacity_per_day_and_more'),
        ('compliance', '0002_harmfulfactor_required_doctors_and_more'),
        ('medical_examinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('fit', 'Годен'), ('unfit', 'Не годен'), ('limited', 'Годен с ограничениями')], max_length=20, verbose_name='Результат')),
                ('findings', models.TextField(blank=True, verbose_name='Заключение')),
                ('recommendations', models.TextField(blank=True, verbose_name='Рекомендации')),
                ('examined_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата осмотра')),
            ],
            options={
                'verbose_name': 'Осмотр врача',
                'verbose_name_plural': 'Осмотры врачей',
            },
        ),
        migrations.CreateModel(
            name='ExaminationRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Маршрутный лист',
                'verbose_name_plural': 'Маршрутные листы',
            },
        ),
        migrations.CreateModel(
            name='LaboratoryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200, verbose_name='Название анализа')),
                ('test_code', models.CharField(blank=True, max_length=50, verbose_name='Код анализа')),
                ('result_value', models.CharField(max_length=100, verbose_name='Результат')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Единица измерения')),
                ('reference_range', models.CharField(blank=True, max_length=100, verbose_name='Референсные значения')),
                ('is_normal', models.BooleanField(default=True, verbose_name='В норме')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выполнения')),
            ],
            options={
                'verbose_name': 'Лабораторный результат',
                'verbose_name_plural': 'Лабораторные результаты',
            },
        ),
        migrations.AddField(
            model_name='medicalexamination',
            name='employer',
            field=models.ForeignKey(blank=True, limit_choices_to={'org_type': 'employer'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employer_examinations', to='organizations.organization', verbose_name='Работодатель'),
        ),
        migrations.AddField(
            model_name='medicalexamination',
            name='qr_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='QR код'),
        ),
        migrations.AddField(
            model_name='medicalexamination',
            name='reason',
            field=models.TextField(blank=True, verbose_name='Причина (для внеочередных)'),
        ),
        migrations.AlterField(
            model_name='medicalexamination',
            name='clinic',
            field=models.ForeignKey(limit_choices_to={'org_type': 'clinic'}, on_delete=django.db.models.deletion.PROTECT, related_name='clinic_examinations', to='organizations.organization', verbose_name='Клиника'),
        ),
        migrations.AlterField(
            model_name='medicalexamination',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='organizations.employee', verbose_name='Сотрудник'),
        ),
        migrations.AddIndex(
            model_name='medicalexamination',
            index=models.Index(fields=['status', 'scheduled_date'], name='medical_exa_status_d412b2_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalexamination',
            index=models.Index(fields=['qr_code'], name='medical_exa_qr_code_a77341_idx'),
        ),
        migrations.AddField(
            model_name='laboratoryresult',
            name='examination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_results', to='medical_examinations.medicalexamination', verbose_name='Осмотр'),
        ),
        migrations.AddField(
            model_name='examinationroute',
            name='doctors_required',
            field=models.ManyToManyField(related_name='routes', to='organizations.organizationmember', verbose_name='Требуемые врачи'),
        ),
        migrations.AddField(
            model_name='examinationroute',
            name='examination',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='medical_examinations.medicalexamination', verbose_name='Осмотр'),
        ),
        migrations.AddField(
            model_name='doctorexamination',
            name='contraindications_found',
            field=models.ManyToManyField(blank=True, to='compliance.medicalcontraindication', verbose_name='Выявленные противопоказания'),
        ),
        migrations.AddField(
            model_name='doctorexamination',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.PROTECT, related_name='examinations_performed', to='organizations.organizationmember', verbose_name='Врач'),
        ),
        migrations.AddField(
            model_name='doctorexamination',
            name='examination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_examinations', to='medical_examinations.medicalexamination', verbose_name='Осмотр'),
        ),
        migrations.AddField(
            model_name='doctorexamination',
            name='harmful_factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_examinations', to='compliance.harmfulfactor', verbose_name='Вредный фактор'),
        ),
        migrations.AlterUniqueTogether(
            name='doctorexamination',
            unique_together={('examination', 'doctor', 'harmful_factor')},
        ),
    ]
