# Generated by Django 4.2.7 on 2025-11-26 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medical_examinations', '0002_doctorexamination_examinationroute_laboratoryresult_and_more'),
        ('organizations', '0002_organization_capacity_per_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('appendix_3', 'Приложение 3 (Список лиц)'), ('calendar_plan', 'Календарный план'), ('final_act', 'Заключительный акт'), ('medical_certificate', 'Справка 075/у'), ('health_passport', 'Паспорт здоровья'), ('sanitary_book', 'Санитарная книжка')], max_length=50, verbose_name='Тип документа')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending_signature', 'Ожидает подписания'), ('signed', 'Подписан'), ('approved', 'Утвержден')], default='draft', max_length=20, verbose_name='Статус')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('content', models.JSONField(default=dict, verbose_name='Содержимое документа')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='Путь к файлу PDF')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('examination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='medical_examinations.medicalexamination', verbose_name='Осмотр')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalendarPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('plan_data', models.JSONField(default=dict, verbose_name='Данные плана (распределение по датам)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(limit_choices_to={'org_type': 'clinic'}, on_delete=django.db.models.deletion.PROTECT, related_name='calendar_plans_received', to='organizations.organization', verbose_name='Клиника')),
                ('document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_plan', to='documents.document', verbose_name='Документ плана')),
                ('employer', models.ForeignKey(limit_choices_to={'org_type': 'employer'}, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_plans', to='organizations.organization', verbose_name='Работодатель')),
            ],
            options={
                'verbose_name': 'Календарный план',
                'verbose_name_plural': 'Календарные планы',
            },
        ),
        migrations.CreateModel(
            name='DocumentSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('clinic', 'Клиника'), ('employer', 'Работодатель'), ('ses', 'СЭС')], max_length=50, verbose_name='Роль подписанта')),
                ('otp_code', models.CharField(blank=True, max_length=10, verbose_name='OTP код')),
                ('otp_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='OTP отправлен')),
                ('otp_verified', models.BooleanField(default=False, verbose_name='OTP подтвержден')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Подписан')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='documents.document', verbose_name='Документ')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_signatures', to=settings.AUTH_USER_MODEL, verbose_name='Подписант')),
            ],
            options={
                'verbose_name': 'Подпись документа',
                'verbose_name_plural': 'Подписи документов',
                'unique_together': {('document', 'signer', 'role')},
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type', 'status'], name='documents_d_documen_80b3b1_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization', 'year'], name='documents_d_organiz_63cb53_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='calendarplan',
            unique_together={('employer', 'year')},
        ),
    ]
