# Generated by Django 4.2.7 on 2025-11-26 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compliance', '0002_harmfulfactor_required_doctors_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='capacity_per_day',
            field=models.IntegerField(default=50, verbose_name='Пропускная способность в день (для клиник)'),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер лицензии'),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, verbose_name='Специализация (для врачей)'),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('hr', 'HR менеджер'), ('safety', 'Инженер по ТБ'), ('doctor', 'Врач'), ('registrar', 'Регистратор'), ('profpathologist', 'Профпатолог')], max_length=20, verbose_name='Роль'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('iin', models.CharField(blank=True, max_length=12, verbose_name='ИИН')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='Отдел/Цех')),
                ('hire_date', models.DateField(verbose_name='Дата приема на работу')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(limit_choices_to={'org_type': 'employer'}, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='organizations.organization', verbose_name='Работодатель')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='compliance.profession', verbose_name='Должность')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
