# Generated by Django 4.2.7 on 2025-11-26 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_harmfulfactor_required_doctors_and_more'),
        ('organizations', '0002_organization_capacity_per_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='compliance.profession', verbose_name='Должность'),
        ),
    ]
