# Generated by Django 4.2.7 on 2025-11-26 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_clinicemployerpartnership'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clinicemployerpartnership',
            new_name='organizatio_clinic__658aa8_idx',
            old_name='organizatio_clinic__idx',
        ),
        migrations.RenameIndex(
            model_name='clinicemployerpartnership',
            new_name='organizatio_employe_5bb208_idx',
            old_name='organizatio_employer_idx',
        ),
        migrations.RenameIndex(
            model_name='clinicemployerpartnership',
            new_name='organizatio_status_323256_idx',
            old_name='organizatio_status_idx',
        ),
    ]
