# Generated by Django 4.2.7 on 2025-11-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_rename_organizatio_clinic__idx_organizatio_clinic__658aa8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Можно извлечь из ИИН или указать вручную', null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], help_text='Можно определить из ИИН или указать вручную', max_length=10, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='employee',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position_start_date',
            field=models.DateField(blank=True, help_text='Для расчета стажа по занимаемой должности', null=True, verbose_name='Дата начала работы на должности'),
        ),
    ]
