# Generated by Django 4.2.7 on 2025-11-26 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HarmfulFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код фактора')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('periodicity_months', models.IntegerField(default=12, verbose_name='Периодичность осмотра (месяцев)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Вредный фактор',
                'verbose_name_plural': 'Вредные факторы',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название профессии')),
                ('is_decreted', models.BooleanField(default=False, verbose_name='Декретированная группа (санкнижка)')),
                ('harmful_factors', models.ManyToManyField(blank=True, related_name='professions', to='compliance.harmfulfactor', verbose_name='Вредные факторы')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicalContraindication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=500, verbose_name='Противопоказание')),
                ('icd_code', models.CharField(blank=True, max_length=20, verbose_name='Код МКБ-10')),
                ('harmful_factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contraindications', to='compliance.harmfulfactor', verbose_name='Вредный фактор')),
            ],
            options={
                'verbose_name': 'Противопоказание',
                'verbose_name_plural': 'Противопоказания',
            },
        ),
    ]
