# Generated by Django 4.2.7 on 2025-11-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='harmfulfactor',
            name='required_doctors',
            field=models.JSONField(default=list, verbose_name='Требуемые врачи (список специализаций)'),
        ),
        migrations.AddField(
            model_name='harmfulfactor',
            name='required_tests',
            field=models.JSONField(default=list, verbose_name='Требуемые анализы (список)'),
        ),
        migrations.AddField(
            model_name='medicalcontraindication',
            name='severity',
            field=models.CharField(choices=[('critical', 'Критическое'), ('moderate', 'Умеренное'), ('minor', 'Незначительное')], default='moderate', max_length=20, verbose_name='Степень тяжести'),
        ),
        migrations.AddField(
            model_name='profession',
            name='keywords',
            field=models.JSONField(default=list, verbose_name='Ключевые слова для авто-маппинга'),
        ),
    ]
